name: Basic test push

on: push

jobs:
  build:
    env:
      SOLUTION_FILE_PATH: .
      BUILD_PLATFORM: "x64"
      BUILD_CONFIGURATION: Release
      OPENSSL_SOLUTION_FILE_PATH: openssl1_1-lite.sln
      OPENSSL_BUILD_PLATFORM: Win64
      ARCH: win64   
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - uses: ilammy/setup-nasm@v1
      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{env.ARCH}}

      - uses: shogo82148/actions-setup-perl@v1
      
      - name: Build OpenSSL    
        run: |
            cd archipelago-client
            cd dep
            git clone -b OpenSSL_1_1_1-stable --depth 1 https://github.com/openssl/openssl.git
            cd openssl
            md x64
            cd x64
            perl ..\Configure VC-WIN64 no-shared
            nmake /S
            
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
        
      - name: Build Project
        run: |
          cd archipelago-client
          dir
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:Platform=${{env.BUILD_PLATFORM}}
          md ${{env.SOLUTION_FILE_PATH}}\${{env.BUILD_CONFIGURATION}}\ds3-client
          
      - name: Store
        uses: actions/upload-artifact@v3
        with:
          name: dinput8
          path: ${{env.SOLUTION_FILE_PATH}}\${{env.BUILD_CONFIGURATION}}\ds3-client\dinput8.dll