name: Basic test push

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - uses: shogo82148/actions-setup-perl@v1
      
      - name: Build OpenSSL    
        run: |
            cd dep
            git clone -b OpenSSL_1_1_1-stable --depth 1 https://github.com/openssl/openssl.git
            cd openssl
            md x86
            cd x86
            perl ..\Configure VC-WIN32 no-shared
            nmake /S