name: Basic test push

on: push

jobs:
  build:
    env:
      SOLUTION_FILE_PATH: archipelago-client
      BUILD_PLATFORM: "x64"
      BUILD_CONFIGURATION: Release
      OPENSSL_SOLUTION_FILE_PATH: openssl1_1-lite.sln
      OPENSSL_BUILD_PLATFORM: Win64
      ARCH: win64   
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - uses: ilammy/setup-nasm@v1
      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{env.ARCH}}

      - uses: shogo82148/actions-setup-perl@v1
      
      - name: Build OpenSSL    
        run: |
            cd archipelago-client
            cd dep
            git clone -b OpenSSL_1_1_1-stable --depth 1 https://github.com/openssl/openssl.git
            cd openssl
            md x64
            cd x64
            perl ..\Configure VC-WIN64A no-shared 
            nmake /S
            
      - uses: montudor/action-zip@v1
        with:
            args: zip -qq -r ${{env.SOLUTION_FILE_PATH}}\openSSL.zip ${{env.SOLUTION_FILE_PATH}}\dep\openssl
            
      - name: Store OpenSSL
        uses: actions/upload-artifact@v3
        with:
          name: openSSL
          path: ${{env.SOLUTION_FILE_PATH}}\openSSL.zip
            
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
        
      - name: Build Project
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:Platform=${{env.BUILD_PLATFORM}}
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:Platform=${{env.BUILD_PLATFORM}}
          
      